services:
  frontend:
    build:
      context: ../fe
      dockerfile: Dockerfile
      args:
        NPM_BUILD_CMD: ${FE_BUILD}
    ports:
    - "5173:5173"
    depends_on:
      - fhir

  fhir:
    container_name: ${APP_CONTAINER_NAME}
    image: hapiproject/hapi:latest
    expose:
      - "8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      - db

  db:
    image: postgres:18
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: hapi
    volumes:
      - hapi_pg_data:/var/lib/postgresql

  auth-db:
    image: postgres:18
    container_name: t1d-auth-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${GO_DB_PASSWORD}
      POSTGRES_USER: ${GO_DB_USER}
      POSTGRES_DB: t1d
    volumes:
      - auth_pg_data:/var/lib/postgresql
      - ../be/initsql:/docker-entrypoint-initdb.d:ro

  auth-app:
    build:
      context: ../be
      dockerfile: Dockerfile
    container_name: t1d-auth-app
    depends_on:
      - auth-db
    environment:
      PORT: 8081
    ports:
      - "8081:8081"

  data-loader:
    image: curlimages/curl:latest
    depends_on:
      - fhir
    volumes:
      - ../mock-data:/data:ro
    restart: "no"
    command:
      - /bin/sh
      - -ec
      - |
        echo "Files mounted in /data:"
        ls -la /data

        echo "Waiting for FHIR server..."
        until curl -fsS http://fhir:8080/fhir/metadata > /dev/null; do
          echo "FHIR not ready, retrying..."
          sleep 3
        done

        echo "FHIR ready. Loading mock-bundle.json..."

        HTTP_CODE=$$(curl -sS -o /tmp/load-response.json -w "%{http_code}" \
          -X POST http://fhir:8080/fhir \
          -H "Content-Type: application/fhir+json" \
          --data-binary @/data/mock-bundle.json)

        echo "FHIR load HTTP code: $$HTTP_CODE"
        echo "FHIR response:"
        cat /tmp/load-response.json
        echo

        if [ "$$HTTP_CODE" -lt 200 ] || [ "$$HTTP_CODE" -ge 300 ]; then
          echo "FHIR data load failed"
          exit 1
        fi

        echo "Mock data loaded successfully."

configs:
  hapi:
    file: ${CONFIG_FILE}

volumes:
  hapi_pg_data:
  auth_pg_data: