services:
  frontend:
    build:
      context: ../fe
      dockerfile: Dockerfile
      args:
        NPM_BUILD_CMD: ${FE_BUILD}
    ports:
    - "5173:5173"
    depends_on:
      - fhir

  fhir:
    container_name: ${APP_CONTAINER_NAME}
    image: hapiproject/hapi:latest
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      - db

  db:
    image: postgres:18
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: hapi
    volumes:
      - ./hapi.postgress.data:/var/lib/postgresql

  auth-db:
    image: postgres:18
    container_name: t1d-auth-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${GO_DB_PASSWORD}
      POSTGRES_USER: ${GO_DB_USER}
      POSTGRES_DB: t1d
    volumes:
      - ./app.postgres.data:/var/lib/postgresql

  auth-app:
    build:
      context: ../be
      dockerfile: Dockerfile
    container_name: t1d-auth-app
    depends_on:
      - auth-db
    environment:
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_USER: ${GO_DB_USER}
      DB_PASSWORD: ${GO_DB_PASSWORD}
      DB_NAME: t1d
      PORT: 8081
    ports:
      - "8081:8081"

configs:
  hapi:
    file: ${CONFIG_FILE}