// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserAndReturnId = `-- name: InsertUserAndReturnId :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id
`

type InsertUserAndReturnIdParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) InsertUserAndReturnId(ctx context.Context, arg InsertUserAndReturnIdParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertUserAndReturnId, arg.Email, arg.PasswordHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
